version: '3.7'

services:
  zombi-app:
    build:
      context: ./
      dockerfile: docker-app
    ports:
      - '8080:8080'
    networks:
      - zombi-network
    environment:
    - NODE_ENV=development
    command:
      sh -c 'npm i && node src/app.js'
    depends_on:
      - zombi-db

  zombi-db:
    image: postgres:11
    volumes:
      - zombi-db-data:/var/lib/postgresql/data
    networks:
      - zombi-network
    restart: always
    environment:
      POSTGRES_PASSWORD: SIBSadmin01
      POSTGRES_USER: zombi
      POSTGRES_DB: zombi
    ports:
      - 5432:5432

networks:
  zombi-network:

volumes:
  zombi-db-data: