version: '3.7'

services:
  zombi-app:
    build:
      context: ./
      dockerfile: docker-app
    ports:
      - '8080:8080'
    networks:
      - zombi-network
    environment:
    - NODE_ENV=development
    env_file:
    - .env
    command:
      sh -c 'npm i && node server/app/zombi.js'
    depends_on:
      - zombi-db
      - zombi-cache

  zombi-db:
    image: postgres:11
    volumes:
      - zombi-db-data:/var/lib/postgresql/data
    networks:
      - zombi-network
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  zombi-cache:
    image: redis
    networks:
      - zombi-network
    ports:
      - 6379:6379

networks:
  zombi-network:

volumes:
  zombi-db-data: